/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.ljk;

public final class R {
    public static final class array {
        public static final int model=0x7f040001;
        public static final int oper_items=0x7f040003;
        public static final int planets=0x7f040000;
        public static final int week=0x7f040002;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int action_list=0x7f020000;
        public static final int add_action=0x7f020001;
        public static final int back=0x7f020002;
        public static final int back_bg=0x7f020003;
        public static final int backs=0x7f020004;
        public static final int calendar=0x7f020005;
        public static final int classtable=0x7f020006;
        public static final int content_bg=0x7f020007;
        public static final int divider=0x7f020008;
        public static final int done_action=0x7f020009;
        public static final int friend=0x7f02000a;
        public static final int icon=0x7f02000b;
        public static final int list_line_normal1=0x7f02000c;
        public static final int list_line_selected1=0x7f02000d;
        public static final int other=0x7f02000e;
        public static final int selector_single=0x7f02000f;
        public static final int setting=0x7f020010;
        public static final int shetuan=0x7f020011;
        public static final int study=0x7f020012;
        public static final int tiyu=0x7f020013;
        public static final int work=0x7f020014;
    }
    public static final class id {
        public static final int DeuList=0x7f060010;
        public static final int ItemImage=0x7f060025;
        public static final int ItemTitle=0x7f060026;
        public static final int LinearLayout01=0x7f060023;
        public static final int ListView01=0x7f060024;
        public static final int RelativeLayout01=0x7f060013;
        public static final int Text02=0x7f060004;
        public static final int add_ok=0x7f06001f;
        public static final int addclass=0x7f060029;
        public static final int addnew=0x7f060012;
        public static final int cancel=0x7f06000a;
        public static final int class_endtime=0x7f06001d;
        public static final int class_starttime=0x7f06001c;
        public static final int class_week=0x7f06001e;
        public static final int date_btn=0x7f060005;
        public static final int day=0x7f06000d;
        public static final int delete=0x7f060020;
        public static final int detail=0x7f060001;
        public static final int deu_typeshow_itemimage=0x7f060016;
        public static final int deu_typeshow_itemtext=0x7f060017;
        public static final int deu_typeshow_listview=0x7f060015;
        public static final int deuactionlist=0x7f060014;
        public static final int et_classname=0x7f060019;
        public static final int et_classroom=0x7f06001a;
        public static final int et_classteacher=0x7f06001b;
        public static final int historylist=0x7f060022;
        public static final int histroy_DeuList=0x7f060021;
        public static final int hour=0x7f060034;
        public static final int listView=0x7f060018;
        public static final int minute=0x7f060035;
        public static final int month=0x7f06000c;
        public static final int return_main=0x7f060011;
        public static final int save=0x7f060009;
        public static final int schedual_classname_listview=0x7f06002a;
        public static final int schedual_classroom_listview=0x7f06002b;
        public static final int schedual_classteacher_listview=0x7f06002d;
        public static final int schedual_classtime_listview=0x7f06002c;
        public static final int schedual_deuList=0x7f060028;
        public static final int schedual_spinner=0x7f060027;
        public static final int setdate=0x7f06000e;
        public static final int settime=0x7f060036;
        public static final int setting_listview=0x7f060032;
        public static final int setting_listview_itemtext=0x7f060033;
        public static final int setting_spinner01=0x7f06002f;
        public static final int setting_spinner02=0x7f060031;
        public static final int setting_spinnerText01=0x7f06002e;
        public static final int setting_spinnerText02=0x7f060030;
        public static final int spinner01=0x7f060003;
        public static final int spinner02=0x7f060008;
        public static final int spinnerText01=0x7f060002;
        public static final int spinnerText02=0x7f060007;
        public static final int time_btn=0x7f060006;
        public static final int title=0x7f060000;
        public static final int type_title=0x7f06000f;
        public static final int year=0x7f06000b;
    }
    public static final class layout {
        public static final int addnew=0x7f030000;
        public static final int date=0x7f030001;
        public static final int deu_action=0x7f030002;
        public static final int deu_action_list=0x7f030003;
        public static final int deu_action_typeshow=0x7f030004;
        public static final int deu_action_typeshow_listitem=0x7f030005;
        public static final int deu_listview=0x7f030006;
        public static final int dialog=0x7f030007;
        public static final int edit=0x7f030008;
        public static final int history=0x7f030009;
        public static final int history_list=0x7f03000a;
        public static final int main_listview=0x7f03000b;
        public static final int main_listview_item=0x7f03000c;
        public static final int schedual=0x7f03000d;
        public static final int schedual_list=0x7f03000e;
        public static final int setting=0x7f03000f;
        public static final int setting_item=0x7f030010;
        public static final int time=0x7f030011;
    }
    public static final class string {
        public static final int action_list=0x7f050002;
        public static final int add_action=0x7f050003;
        public static final int addnew=0x7f050011;
        public static final int app_name=0x7f050001;
        public static final int calendar=0x7f050005;
        public static final int cancel=0x7f050008;
        public static final int classday=0x7f05001c;
        public static final int classname=0x7f050019;
        public static final int classroom=0x7f05001b;
        public static final int classteacher=0x7f05001d;
        public static final int classtime=0x7f05001a;
        public static final int confirm_delete=0x7f050017;
        public static final int date=0x7f050014;
        public static final int delete=0x7f05000d;
        public static final int delete_success=0x7f050018;
        public static final int detail=0x7f05000a;
        public static final int details=0x7f050013;
        public static final int deulist=0x7f050009;
        public static final int done_action=0x7f050004;
        public static final int edit=0x7f05000f;
        public static final int hello=0x7f050000;
        public static final int history=0x7f050020;
        public static final int ok=0x7f050007;
        public static final int operate=0x7f05001f;
        public static final int remidtype=0x7f05000c;
        public static final int return_main=0x7f050010;
        public static final int schedual=0x7f050015;
        public static final int setting=0x7f050006;
        public static final int startend=0x7f05001e;
        public static final int time=0x7f05000b;
        public static final int title=0x7f050012;
        public static final int typeshow=0x7f05000e;
        public static final int warn=0x7f050016;
    }
}
